# Linux GCC Makefile
# Created by O. Conrad

PROJECTS = saga_core modules modules_contrib modules_geostatistics modules_projection modules_io modules_recreations modules_simulation modules_terrain_analysis modules_lectures

all:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux); done

clean:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux clean); done

.PHONY: all clean
