# Linux GCC Makefile
# Created by O. Conrad

PROJECTS = ta_profiles ta_preprocessor ta_morphometry ta_lighting ta_hydrology ta_channels

all:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux); done

clean:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux clean); done

.PHONY: all clean
