/* config.h.cmake.  This file is autogenerated by cmake. Do not edit */
/**
 * This file is auto-generated by cmake. Do not edit it directly
 * Edits should be done to [project root]/cmake/config.h.cmake
 * and [project root]/cmake/Config.cmake
 */

/* Version number of package */
#cmakedefine VERSION @SAGA_VERSION_STRING@

/* build with GUI and interactive tools */
#cmakedefine WITH_GUI

/* build with HDF5 */
#cmakedefine WITH_HDF5
