# Linux GCC Makefile
# Created by O. Conrad

PROJECTS = esri_e00 gps gdal grid shapes table

all:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux); done

clean:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux clean); done

.PHONY: all clean
