# Linux GCC Makefile
# Created by O. Conrad

PROJECTS = shapes grid gps esri_e00 table

all:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux); done

clean:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux clean); done

.PHONY: all clean
