# Linux GCC Makefile
# Created by O. Conrad

PROJECTS = shapes_tools shapes_polygons shapes_points shapes_lines shapes_grid shapes_transect

all:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux); done

clean:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux clean); done

.PHONY: all clean
