# Linux GCC Makefile
# Created by O. Conrad

PROJECTS = geostatistics_points geostatistics_kriging geostatistics_kriging_variogram geostatistics_grid

all:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux); done

clean:
	@for i in $(PROJECTS); do (cd $$i && $(MAKE) -fmakefile.linux clean); done

.PHONY: all clean
